version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: taskmanager-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: taskmanager_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: taskmanager-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/taskmanager_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - mysqldb

  frontend:
    build: ./frontend
    container_name: taskmanager-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
